// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUpW4-M7_3R8_QWdAQUPEsJw0hMTLlSVA',
    appId: '1:727044072264:web:3769bf3118de42e707097d',
    messagingSenderId: '727044072264',
    projectId: 'e-commerce-app-38422',
    authDomain: 'e-commerce-app-38422.firebaseapp.com',
    storageBucket: 'e-commerce-app-38422.firebasestorage.app',
    measurementId: 'G-7GJDSJHVVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuKLQF29JWbkd8JLcyypo7Uda5wNyTIf8',
    appId: '1:727044072264:android:25da35e76d6d5a1307097d',
    messagingSenderId: '727044072264',
    projectId: 'e-commerce-app-38422',
    storageBucket: 'e-commerce-app-38422.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx2rE00nQ6u7wVe3QgY9uKoC8NPZOUZtc',
    appId: '1:727044072264:ios:b5269b1383e321ae07097d',
    messagingSenderId: '727044072264',
    projectId: 'e-commerce-app-38422',
    storageBucket: 'e-commerce-app-38422.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx2rE00nQ6u7wVe3QgY9uKoC8NPZOUZtc',
    appId: '1:727044072264:ios:b5269b1383e321ae07097d',
    messagingSenderId: '727044072264',
    projectId: 'e-commerce-app-38422',
    storageBucket: 'e-commerce-app-38422.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUpW4-M7_3R8_QWdAQUPEsJw0hMTLlSVA',
    appId: '1:727044072264:web:a97ddc89c3fa4efe07097d',
    messagingSenderId: '727044072264',
    projectId: 'e-commerce-app-38422',
    authDomain: 'e-commerce-app-38422.firebaseapp.com',
    storageBucket: 'e-commerce-app-38422.firebasestorage.app',
    measurementId: 'G-MJ967T0D0M',
  );
}
